name: "emsdk"

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20.x]
    steps:
      - uses: mymindstorm/setup-emsdk@v11
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Submodule Workaround
        run: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
      - name: Init Submodules
        run: npm run init
      - name: Install Submodules
        run: npm run submodule:build
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test Run
        run: node sample/node/hoge3.js
