name: "emsdk"

on:
  push:


jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [18.x]
    steps:
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.22
      - name: Verify
        run: emcc -v
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install build-essential
        run: |
          sudo apt -y update
          sudo apt -y upgrade
          sudo apt -y install build-essential
      - name: Submodule Workaround
        run: |
          sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          sed -i 's/git@github.com:/https:\/\/github.com\//' ./submodules/boost/.gitmodules
      - name: Init Submodules
        run: npm run init
      - name: Build Submodules
        run: npm run submodule:build
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test Run
        run: node sample/node/hoge3.js
